[package]
name = "future-local-storage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pin-project-lite = "0.2.13"
state = { version = "0.6.0", features = ["tls"] }

[dev-dependencies]
pretty_assertions = "1.4.0"
tokio = { version = "1.0", features = ["macros", "rt", "rt-multi-thread"] }

[lints.clippy]
pedantic = "warn"
module_name_repetitions = "allow"
missing_panics_doc = "allow"
