name: "Tests"
on:
  pull_request:

jobs:
  lints:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: nixpkgs-cross-overlay

      - name: "Check formatting"
        run: nix flake check

      - name: "Run linters"
        run: nix run .#ci-lints

      - name: "Run semver checks"
        run: nix run .#ci-semver-checks

  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: nixpkgs-cross-overlay

      - name: "Run tests"
        run: nix run .#ci-tests

      - name: "Run miri tests"
        run: nix run .#ci-miri-tests
