name: "Tests"
on:
  pull_request:

jobs:
  lints:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v12
        with:
          name: nixpkgs-cross-overlay
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: "Check formatting"
        run: nix flake check

      - name: "Run linters"
        run: nix develop --command ci-run-lints

  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v12
        with:
          name: nixpkgs-cross-overlay
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: "Run cargo tests"
        run: nix develop --command ci-run-tests

  miri-checks:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v12
        with:
          name: nixpkgs-cross-overlay
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: "Run miri tests"
        run: nix develop --command ci-run-miri-tests
