name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  semver-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31

      - name: Run semver compatibility checks
        run: nix run .#check-cargo-semver
      - name: Run cargo publish compatibility checks
        run: nix run .#check-cargo-publish

  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31

      - name: Run checks
        run: nix flake check
